[package]
name = "elo-calc"
version = "0.1.0"
authors = ["Josh Finnie <josh@jfin.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
